<?php

/*********************************************************************
* Extension configuration file for ext "flush_language_cache".
*
* Generated by ext 04-09-2015 14:40 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Flush language cache',
    'description' => 'Adds an item to the flush cache menu to clear just the language (l10n) cache. Also provides a command-line tool for that.',
    'category' => 'be',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'author' => 'Francois Suter',
    'author_email' => 'typo3@cobweb.ch',
    'author_company' => '',
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
